/* Generated By:JJTree: Do not edit this line. ASTArg_DELC.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.smallscript.parser;

public
class ASTArg_DELC extends SimpleNode {
  public ASTArg_DELC(int id) {
    super(id);
  }

  public ASTArg_DELC(SmallScriptParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SmallScriptParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c29b9196e4ac4fb1e8afb02177b1dc61 (do not edit this line) */
