/* Generated By:JJTree: Do not edit this line. ASTArrayAssignment.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.smallscript.parser;

public
class ASTArrayAssignment extends SimpleNode {
  public ASTArrayAssignment(int id) {
    super(id);
  }

  public ASTArrayAssignment(SmallScriptParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SmallScriptParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=707037e44b67a01e19c44b5c04f66c2b (do not edit this line) */
