/* Generated By:JJTree: Do not edit this line. ASTDblEqualNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.smallscript.parser;

public
class ASTDblEqualNode extends SimpleNode {
  public ASTDblEqualNode(int id) {
    super(id);
  }

  public ASTDblEqualNode(SmallScriptParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SmallScriptParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f855824914d7af74257721c33feee0c5 (do not edit this line) */
