/* Generated By:JJTree: Do not edit this line. ASTExpressionParameters.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.smallscript.parser;

public
class ASTExpressionParameters extends SimpleNode {
  public ASTExpressionParameters(int id) {
    super(id);
  }

  public ASTExpressionParameters(SmallScriptParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SmallScriptParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=92da4064d20b1c5a52f975494d5d1cea (do not edit this line) */
