/* Generated By:JJTree: Do not edit this line. ASTFunctionNameId.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.smallscript.parser;

public
class ASTFunctionNameId extends SimpleNode {
  public ASTFunctionNameId(int id) {
    super(id);
  }

  public ASTFunctionNameId(SmallScriptParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SmallScriptParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=413a0b38621fd72adf7dc0ee747830eb (do not edit this line) */
