/* Generated By:JJTree: Do not edit this line. ASTSubractExpr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.smallscript.parser;

public
class ASTSubractExpr extends SimpleNode {
  public ASTSubractExpr(int id) {
    super(id);
  }

  public ASTSubractExpr(SmallScriptParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SmallScriptParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=84ac0cbbf90eba7412f9c0054fb647d2 (do not edit this line) */
