/* Generated By:JJTree: Do not edit this line. ASTVAL_DELC.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.smallscript.parser;

public
class ASTVAL_DELC extends SimpleNode {
  public ASTVAL_DELC(int id) {
    super(id);
  }

  public ASTVAL_DELC(SmallScriptParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SmallScriptParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b58c23df338094027a6a52ea2c18dbd4 (do not edit this line) */
