/* Generated By:JJTree: Do not edit this line. ASTVAR_DELC.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.smallscript.parser;

public
class ASTVAR_DELC extends SimpleNode {
  public ASTVAR_DELC(int id) {
    super(id);
  }

  public ASTVAR_DELC(SmallScriptParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SmallScriptParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=cb5276ba2c3992925163dffcd0461cef (do not edit this line) */
