/* Generated By:JavaCC: Do not edit this line. ExampleTreeConstants.java Version 5.0 */
package com.smallscript.parser;

public interface ExampleTreeConstants
{
  public int JJTSTART = 0;
  public int JJTEXPRESSION = 1;
  public int JJTADDITIVEEXPRESSION = 2;
  public int JJTMULTIPLICATIVEEXPRESSION = 3;
  public int JJTUNARYEXPRESSION = 4;
  public int JJTIDENTIFIER = 5;
  public int JJTINTEGER = 6;


  public String[] jjtNodeName = {
    "Start",
    "Expression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "UnaryExpression",
    "Identifier",
    "Integer",
  };
}
/* JavaCC - OriginalChecksum=f4172c72d5b46db1ea7b895543a367f2 (do not edit this line) */
