/* Generated By:JavaCC: Do not edit this line. SmallScriptParserVisitor.java Version 5.0 */
package com.smallscript.parser;

public interface SmallScriptParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTstart node, Object data);
  public Object visit(ASTStatement node, Object data);
  public Object visit(ASTImport node, Object data);
  public Object visit(ASTCharLiteral node, Object data);
  public Object visit(ASTBreak node, Object data);
  public Object visit(ASTVAR_DELC node, Object data);
  public Object visit(ASTVAL_DELC node, Object data);
  public Object visit(ASTArg_DELC node, Object data);
  public Object visit(ASTAssignment node, Object data);
  public Object visit(ASTPrint node, Object data);
  public Object visit(ASTidentifier node, Object data);
  public Object visit(ASTVariable node, Object data);
  public Object visit(ASTIfStatement node, Object data);
  public Object visit(ASTElse node, Object data);
  public Object visit(ASTWhileStatement node, Object data);
  public Object visit(ASTLoopStatement node, Object data);
  public Object visit(ASTFunction node, Object data);
  public Object visit(ASTParameters node, Object data);
  public Object visit(ASTParameter node, Object data);
  public Object visit(ASTFunctionCall node, Object data);
  public Object visit(ASTExpressionParameters node, Object data);
  public Object visit(ASTReturnStatement node, Object data);
  public Object visit(ASTStatementBlock node, Object data);
  public Object visit(ASTType node, Object data);
  public Object visit(ASTexpression node, Object data);
  public Object visit(ASTLTNode node, Object data);
  public Object visit(ASTGTNode node, Object data);
  public Object visit(ASTLENode node, Object data);
  public Object visit(ASTGENode node, Object data);
  public Object visit(ASTDblEqualNode node, Object data);
  public Object visit(ASTAddExpr node, Object data);
  public Object visit(ASTSubractExpr node, Object data);
  public Object visit(ASTMultiplyExpr node, Object data);
  public Object visit(ASTDivideExpr node, Object data);
  public Object visit(ASTModuloExpr node, Object data);
  public Object visit(ASTunaryExpression node, Object data);
  public Object visit(ASTNegateExpr node, Object data);
  public Object visit(ASTArrayLiteral node, Object data);
  public Object visit(ASTArrayAccess node, Object data);
  public Object visit(ASTArrayAssignment node, Object data);
  public Object visit(ASTStringLiteral node, Object data);
  public Object visit(ASTnumberExpression node, Object data);
  public Object visit(ASTNumber node, Object data);
  public Object visit(ASTVarialbleValue node, Object data);
}
/* JavaCC - OriginalChecksum=7c8351ffe17c3f63d1ec26289e9a8694 (do not edit this line) */
