/* Generated By:JavaCC: Do not edit this line. SmallScriptParserTreeConstants.java Version 5.0 */
package com.smallscript.parser;

public interface SmallScriptParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTSTATEMENT = 1;
  public int JJTIMPORT = 2;
  public int JJTCHARLITERAL = 3;
  public int JJTBREAK = 4;
  public int JJTVAR_DELC = 5;
  public int JJTVAL_DELC = 6;
  public int JJTARG_DELC = 7;
  public int JJTASSIGNMENT = 8;
  public int JJTPRINT = 9;
  public int JJTIDENTIFIER = 10;
  public int JJTVARIABLE = 11;
  public int JJTIFSTATEMENT = 12;
  public int JJTELSE = 13;
  public int JJTWHILESTATEMENT = 14;
  public int JJTLOOPSTATEMENT = 15;
  public int JJTFUNCTION = 16;
  public int JJTPARAMETERS = 17;
  public int JJTPARAMETER = 18;
  public int JJTFUNCTIONCALL = 19;
  public int JJTEXPRESSIONPARAMETERS = 20;
  public int JJTRETURNSTATEMENT = 21;
  public int JJTSTATEMENTBLOCK = 22;
  public int JJTTYPE = 23;
  public int JJTEXPRESSION = 24;
  public int JJTVOID = 25;
  public int JJTLTNODE = 26;
  public int JJTGTNODE = 27;
  public int JJTLENODE = 28;
  public int JJTGENODE = 29;
  public int JJTDBLEQUALNODE = 30;
  public int JJTADDEXPR = 31;
  public int JJTSUBRACTEXPR = 32;
  public int JJTMULTIPLYEXPR = 33;
  public int JJTDIVIDEEXPR = 34;
  public int JJTMODULOEXPR = 35;
  public int JJTUNARYEXPRESSION = 36;
  public int JJTNEGATEEXPR = 37;
  public int JJTARRAYLITERAL = 38;
  public int JJTARRAYACCESS = 39;
  public int JJTARRAYASSIGNMENT = 40;
  public int JJTSTRINGLITERAL = 41;
  public int JJTNUMBEREXPRESSION = 42;
  public int JJTNUMBER = 43;
  public int JJTVARIALBLEVALUE = 44;


  public String[] jjtNodeName = {
    "start",
    "Statement",
    "Import",
    "CharLiteral",
    "Break",
    "VAR_DELC",
    "VAL_DELC",
    "Arg_DELC",
    "Assignment",
    "Print",
    "identifier",
    "Variable",
    "IfStatement",
    "Else",
    "WhileStatement",
    "LoopStatement",
    "Function",
    "Parameters",
    "Parameter",
    "FunctionCall",
    "ExpressionParameters",
    "ReturnStatement",
    "StatementBlock",
    "Type",
    "expression",
    "void",
    "LTNode",
    "GTNode",
    "LENode",
    "GENode",
    "DblEqualNode",
    "AddExpr",
    "SubractExpr",
    "MultiplyExpr",
    "DivideExpr",
    "ModuloExpr",
    "unaryExpression",
    "NegateExpr",
    "ArrayLiteral",
    "ArrayAccess",
    "ArrayAssignment",
    "StringLiteral",
    "numberExpression",
    "Number",
    "VarialbleValue",
  };
}
/* JavaCC - OriginalChecksum=e3c118350986942f726309f43f6ce301 (do not edit this line) */
